baseURL = 'https://cloud-cipher.co.uk'
languageCode = 'en-gb'
title = 'Cloud Cipher Ltd'
disableKinds = ['taxonomy', 'term']
disableHugoGeneratorInject = true
[markup.goldmark.renderer]
unsafe = true
