baseURL = 'https://fortiguardltd.com'
languageCode = 'en-gb'
title = 'FortiGuard Limited'
disableKinds = ['taxonomy', 'term']
disableHugoGeneratorInject = true
[markup.goldmark.renderer]
unsafe = true
